name: Terraform

on:
  pull_request:
    paths:
      - "terraform/**"
  push:
    branches: [main]
    paths:
      - "terraform/**"

jobs:
  terraform-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: terraform/dev
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.x"
      
      - name: Terraform fmt
        run: terraform fmt -check -recursive
      
      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validation
        run: terraform validate